include(PpBrowserTesting)

add_executable(pp_browser_feature_registration_test registration_client_test.cpp)
target_link_libraries(pp_browser_feature_registration_test PRIVATE
  pp_feature_registration
  GTest::gtest
  GTest::gtest_main)
pp_browser_apply_warnings(pp_browser_feature_registration_test)
pp_browser_add_gtest(pp_browser_feature_registration_test)
