pp_browser_add_base_library(pp_base_net
  SOURCES
    HttpClient.cpp
    RelayApiSignPayload.cpp
    RelaySignBytes.cpp
    RegistrationClientUtil.cpp
    RegistrationSignPayload.cpp
    ServiceClientFactory.cpp
    ServiceClientsImpl.cpp
  PUBLIC_LIBS
    pp_base_error
    pp_base_data
    pp_base_crypto
    pp_base_people
    pp_base_messaging
    nlohmann_json::nlohmann_json
    CURL::libcurl)

if(PP_BROWSER_BUILD_TESTS)
  add_subdirectory(tests)
endif()
