# libp2p fork configuration (product glue lives in src/base/p2p).

include(PpBrowserWarnings)
include(PpBrowserLib)

function(pp_browser_define_libp2p_options)
  if(PP_BROWSER_IS_MOBILE)
    set(PP_BROWSER_LIBP2P_TESTING_DEFAULT OFF)
  else()
    set(PP_BROWSER_LIBP2P_TESTING_DEFAULT ON)
  endif()
  option(PP_BROWSER_LIBP2P_TESTING "Build in-tree libp2p unit tests" ${PP_BROWSER_LIBP2P_TESTING_DEFAULT})
  option(PP_BROWSER_LIBP2P_EXAMPLES "Build in-tree libp2p examples" OFF)
  option(PP_BROWSER_LIBP2P_COVERAGE "Enable libp2p gcovr coverage targets" OFF)
endfunction()

function(pp_browser_configure_libp2p_fork)
  pp_configure_status("Configuring in-tree libp2p (src/lib/libp2p)...")

  set(PACKAGE_MANAGER vendored CACHE STRING "" FORCE)
  if(PP_BROWSER_IS_MOBILE)
    set(TESTING OFF CACHE BOOL "" FORCE)
    set(EXAMPLES OFF CACHE BOOL "" FORCE)
    set(COVERAGE OFF CACHE BOOL "" FORCE)
  else()
    set(TESTING ${PP_BROWSER_LIBP2P_TESTING} CACHE BOOL "Build libp2p tests" FORCE)
    set(EXAMPLES ${PP_BROWSER_LIBP2P_EXAMPLES} CACHE BOOL "Build libp2p examples" FORCE)
    set(COVERAGE ${PP_BROWSER_LIBP2P_COVERAGE} CACHE BOOL "libp2p coverage" FORCE)
  endif()
  set(CLANG_TIDY OFF CACHE BOOL "" FORCE)
  set(CLANG_FORMAT OFF CACHE BOOL "" FORCE)
endfunction()
